### ISSUE TITLE
Unable to set TLS input encryption

### ISSUE THREAD

**Issue by Dacesilian** [logmatic/beats-forwarder#6]
/app/beats-forwarder/beats-forwarder -c etc/config.yml
INFO[0000] Register 'syslog' as the remote output
INFO[0000] Setting an encrypted communication for the input
**FATA[0000] tls: neither Certificates nor GetCertificate set in Config**

```
tls:
    # By default, TLS is disabled
    enable: true

    # Path to the ca file
    ca_path: certs/MyRootCA.pem

    # Path to the cert file
    cert_path: certs/MyServer.pem

    # Path to the key file
    key_path: certs/MyServer.key

```
Specifying full path to certs/key doesn't help either.
